# Generated by Django 4.2.4 on 2023-08-17 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_syte', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='export',
            new_name='excerpt',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(50)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
