# Generated by Django 4.2.4 on 2023-08-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_syte', '0006_rename_data_post_date_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='my_syte.tag'),
        ),
    ]
