# Generated by Django 4.2.4 on 2023-08-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_syte', '0007_alter_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
